// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVBA-8ttn63xyz2VHSbSfFF3ibU9kYVVc',
    appId: '1:154654685348:web:d882b6eb71648c2c3d4e31',
    messagingSenderId: '154654685348',
    projectId: 'app3-e4025',
    authDomain: 'app3-e4025.firebaseapp.com',
    storageBucket: 'app3-e4025.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQjBN_jgJ6uhmi-bWFw2YzN4RbD9lWC1Y',
    appId: '1:154654685348:android:ce17bac3cb31cd1e3d4e31',
    messagingSenderId: '154654685348',
    projectId: 'app3-e4025',
    storageBucket: 'app3-e4025.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAm61i2Bdz0DtcXgojDg8X7WzuKvLn33nw',
    appId: '1:154654685348:ios:e84d85cca46ae5193d4e31',
    messagingSenderId: '154654685348',
    projectId: 'app3-e4025',
    storageBucket: 'app3-e4025.appspot.com',
    iosClientId: '154654685348-eo4vcqpl27aaligpjpec4vlp4idt8o60.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAm61i2Bdz0DtcXgojDg8X7WzuKvLn33nw',
    appId: '1:154654685348:ios:66be1b07f9a805ab3d4e31',
    messagingSenderId: '154654685348',
    projectId: 'app3-e4025',
    storageBucket: 'app3-e4025.appspot.com',
    iosClientId: '154654685348-cuc03bce3rf7k35oubviq9mslu7ir9j2.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
