// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXXTNy-Ze1IGMfOn8YaABwO5--vLBaWxw',
    appId: '1:955146734110:web:accffb3e3c987aca6d7c0f',
    messagingSenderId: '955146734110',
    projectId: 'flutter-chat-app-ba35d',
    authDomain: 'flutter-chat-app-ba35d.firebaseapp.com',
    storageBucket: 'flutter-chat-app-ba35d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkHUrNJ004pQOD_-pDzt20VBf48j3VP0k',
    appId: '1:955146734110:android:1e32071335b1a1016d7c0f',
    messagingSenderId: '955146734110',
    projectId: 'flutter-chat-app-ba35d',
    storageBucket: 'flutter-chat-app-ba35d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDo0m_g9zIsQnBZ3jF3b7xY8DGD5bC7A8U',
    appId: '1:955146734110:ios:d72962694b7fe85e6d7c0f',
    messagingSenderId: '955146734110',
    projectId: 'flutter-chat-app-ba35d',
    storageBucket: 'flutter-chat-app-ba35d.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDo0m_g9zIsQnBZ3jF3b7xY8DGD5bC7A8U',
    appId: '1:955146734110:ios:216393ec99c5e4566d7c0f',
    messagingSenderId: '955146734110',
    projectId: 'flutter-chat-app-ba35d',
    storageBucket: 'flutter-chat-app-ba35d.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
